In [2]:
import pandas as pd

## Q1

In [3]:
pd.__version__

'2.3.1'

## Q2

In [4]:
df=pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [5]:
df.count

<bound method DataFrame.count of       engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003 

## Q3

In [6]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

## Q4

In [7]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

## Q5

In [8]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

## Q6

In [9]:
df['horsepower'].median()

np.float64(149.0)

In [10]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [13]:
df['horsepower'].isnull().sum()

np.int64(708)

In [ ]:
df1=df['horsepower'].fillna(df['horsepower'].mode()[0])
df1.isnull().sum()

np.int64(0)

In [15]:
df1.median()

np.float64(152.0)

## Q7

In [16]:
dfasia=df[df['origin'] == 'Asia']
dfasia.count()

engine_displacement    3247
num_cylinders          3099
horsepower             3013
vehicle_weight         3247
acceleration           2933
model_year             3247
origin                 3247
fuel_type              3247
drivetrain             3247
num_doors              3072
fuel_efficiency_mpg    3247
dtype: int64

In [21]:
dfasialite=dfasia[['vehicle_weight','model_year']]
dfasialitenp=dfasialite.head(7).to_numpy()

In [25]:
X=dfasialitenp
tX=X.T


In [26]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [27]:
tX

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [35]:
XTX = tX.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [29]:
y=[1100, 1300, 800, 900, 1000, 1100, 1200]
y

[1100, 1300, 800, 900, 1000, 1100, 1200]

In [36]:
import numpy as np
XTXi = np.linalg.inv(XTX)
XTXi

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [37]:
wTemp = XTXi.dot(tX)
w = wTemp.dot(y)
w   

array([0.01386421, 0.5049067 ])

In [38]:
w.sum()

np.float64(0.5187709081074016)